use_frameworks!

platform :ios, '13.0'

target 'Example' do
  pod 'iProov', :path => '../'
  pod 'iProovAPIClient', :path => '../'
  pod 'MBProgressHUD'
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    # Xcode 14.3+ workaround for dependencies with deployment target <iOS11
    if ['MBProgressHUD'].include? target.name
      target.build_configurations.each do |config|
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
      end
    end
  end
end
