platform :ios, '9.0'

target 'WaterlooBank' do
  use_frameworks!

  pod 'iProov', :git => 'git@github.com:iProov/ios.git', :branch => 'nextgen'
  pod 'Alamofire', '~> 4.0'
  pod 'Alamofire-SwiftyJSON', '~> 3.0'
  pod 'MBProgressHUD'

end
