platform :ios, '9.0'

target 'WaterlooBank' do
  use_frameworks!

  pod 'iProov', :path => '../'
  pod 'Alamofire', '~> 4.0'
  pod 'Alamofire-SwiftyJSON', '~> 3.0'
  pod 'MBProgressHUD'

end

post_install do |installer|
    installer.pods_project.targets.each do |target|
      if ['KeychainAccess', 'Socket.IO-Client-Swift', 'SwiftyJSON'].include? target.name
        target.build_configurations.each do |config|
            config.build_settings['BUILD_LIBRARY_FOR_DISTRIBUTION'] = 'YES'
        end
      end
    end
end
