platform :ios, '9.0'

target 'WaterlooBank' do
  use_frameworks!

  pod 'iProov', :path => '../'
  pod 'iProovAPIClient', :git => 'https://github.com/iProov/ios-api-client.git'
  pod 'MBProgressHUD'

end
