platform :ios, '9.0'

target 'WaterlooBankObjC' do
  use_frameworks!

  # Pods for WaterlooBankObjC
  pod 'iProov', :git => 'https://github.com/iProov/iproov-ios-pod.git'

end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        if target.name == 'Socket.IO-Client-Swift'
            target.build_configurations.each do |config|
                config.build_settings['SWIFT_VERSION'] = '3.2'
            end
        end
    end
end
