# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'WaterlooBankObjC' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  use_frameworks!

  # Pods for WaterlooBankObjC
  pod 'iProov', :git => 'https://github.com/iProov/iproov-ios-pod.git'

end

